cors:
    origin: ${CORS_ORIGINS}
server:
    port: ${PORT}
spring:
    application:
        name: api-person
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USERNAME}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    sql:
        init:
            mode: always
            schema-locations: classpath:schema.sql